defmodule Mix.Tasks.Archdo.AuditDocCoverage do
  @dialyzer :no_undefined_callbacks
  @shortdoc "Audit ARCHITECTURE_RULES.md against the rule registry"
  @moduledoc """
  Compares the rule registry against `ARCHITECTURE_RULES.md` and
  reports any rule that is registered but not documented (missing)
  or documented but no longer in the registry (stale).

      mix archdo.audit_doc_coverage
      mix archdo.audit_doc_coverage --refresh-baseline

  ## Output

  Prints two lists:

    * **Missing** — registered rules with no `### N.M Title` heading
      in the doc.
    * **Stale** — `### N.M Title` headings whose id doesn't appear
      in the registry (renamed, removed, or typo).

  Exit code:

    * `0` — fully covered: 0 missing, 0 stale.
    * `1` — gap exists.

  ## Baseline

  The current undocumented backlog lives in
  `priv/doc_coverage_baseline.txt`. The doc-coverage regression
  test (`test/doc_coverage_test.exs`) uses it to fail CI when a
  *new* rule is added without docs while tolerating the
  acknowledged backlog.

  Use `--refresh-baseline` to write the current missing list into
  the baseline file. Do this only when you've reviewed the addition
  consciously (e.g. after writing rule docs, to remove ids from the
  baseline).
  """

  use Mix.Task

  alias Archdo.DocCoverage

  @doc_path "ARCHITECTURE_RULES.md"
  @baseline_path "priv/doc_coverage_baseline.txt"

  @impl Mix.Task
  def run(args) do
    refresh? = "--refresh-baseline" in args

    registry = DocCoverage.registered_rule_ids()
    doc = @doc_path |> File.read!() |> DocCoverage.documented_rule_ids()

    case DocCoverage.audit(registry, doc) do
      {:ok, _} ->
        Mix.shell().info("✓ Doc coverage complete — every registered rule is documented.")
        :ok

      {:gap, %{missing: missing, stale: stale}} ->
        report(missing, stale, refresh?)

        case refresh? do
          true ->
            write_baseline(missing)
            :ok

          false ->
            System.at_exit(fn _ -> exit({:shutdown, 1}) end)
            :gap
        end
    end
  end

  defp report(missing, stale, refresh?) do
    Mix.shell().info("Doc-coverage audit: #{@doc_path}")
    Mix.shell().info("")
    Mix.shell().info("  Registered rules:    #{length(registered_total())}")
    Mix.shell().info("  Documented rules:    #{length(documented_total())}")
    Mix.shell().info("  Missing from doc:    #{length(missing)}")
    Mix.shell().info("  Stale doc entries:   #{length(stale)}")
    Mix.shell().info("")

    print_list("Missing (registered but not in doc):", missing)
    print_list("Stale (in doc but not in registry):", stale)

    refresh_hint(refresh?, missing)
  end

  defp registered_total, do: DocCoverage.registered_rule_ids()

  defp documented_total do
    @doc_path |> File.read!() |> DocCoverage.documented_rule_ids()
  end

  defp print_list(_label, []), do: :ok

  defp print_list(label, ids) do
    Mix.shell().info(label)
    Enum.each(ids, fn id -> Mix.shell().info("  - #{id}") end)
    Mix.shell().info("")
  end

  defp refresh_hint(true, _), do: :ok

  defp refresh_hint(false, []), do: :ok

  defp refresh_hint(false, _missing) do
    Mix.shell().info(
      "Run `mix archdo.audit_doc_coverage --refresh-baseline` to write the current\n" <>
        "missing list into #{@baseline_path}.\n"
    )
  end

  defp write_baseline(missing) do
    File.mkdir_p!(Path.dirname(@baseline_path))

    body =
      """
      # Doc-coverage baseline. Generated by `mix archdo.audit_doc_coverage --refresh-baseline`.
      #
      # Each line is a rule id we acknowledge as currently undocumented in
      # ARCHITECTURE_RULES.md. As rules get documented, remove their id
      # from this file. Empty file = full coverage.
      #
      # Lines starting with # are comments. Blank lines are ignored.
      """ <> Enum.join(missing, "\n") <> "\n"

    File.write!(@baseline_path, body)
    Mix.shell().info("Wrote baseline → #{@baseline_path} (#{length(missing)} ids)")
  end
end
