defmodule Archdo.Rules.Testing.ChangesetErrorsAccessInTest do
  @moduledoc false
  @behaviour Archdo.Rule

  alias Archdo.{AST, Diagnostic, Fix}

  @impl true
  def id, do: "7.31"

  @impl true
  def description,
    do: "Test reaches into `changeset.errors` directly — use the `errors_on/1` helper"

  @impl true
  def analyze(file, ast, _opts) do
    case AST.test_file?(file) do
      false -> []
      true -> find_errors_access(file, ast)
    end
  end

  defp find_errors_access(file, ast) do
    ast
    |> AST.find_all(&errors_field_access?/1)
    |> Enum.map(fn node -> build_diagnostic(file, line_of(node)) end)
  end

  # `cs.errors` parses as `{{:., _, [{var, _, _}, :errors]}, _, []}`.
  defp errors_field_access?({{:., _, [{var, _, ctx}, :errors]}, _, []})
       when is_atom(var) and (is_atom(ctx) or is_nil(ctx)) and var != :__MODULE__,
       do: true

  defp errors_field_access?(_), do: false

  defp line_of({_, meta, _}), do: AST.line(meta)

  defp build_diagnostic(file, line) do
    Diagnostic.info("7.31",
      title: "Reach into `changeset.errors` — prefer `errors_on/1` helper",
      message:
        "Test reads `changeset.errors` directly. The standard Phoenix/Ecto test helper " <>
          "`errors_on/1` formats errors as `%{field => [message, ...]}`, which gives " <>
          "structural pattern-match assertions and far better failure diffs.",
      why:
        "`changeset.errors` is `[field: {message, opts}, ...]` — a keyword list of raw " <>
          "templates with placeholder substitutions. Asserting against that shape couples " <>
          "the test to internal representation: changing the message, adding a placeholder, " <>
          "or moving the validation breaks the assertion noise. `errors_on/1` (generated by " <>
          "`mix phx.gen.context`, available in `MyApp.DataCase`) interpolates the messages " <>
          "and returns a clean map. Pattern-matching `%{email: [\"can't be blank\"]}` reads " <>
          "as the spec the validation enforces.",
      alternatives: [
        Fix.new(
          summary: "Use the `errors_on/1` helper",
          detail:
            "# In test/support/data_case.ex (Phoenix-generated):\n" <>
              "def errors_on(changeset) do\n" <>
              "  Ecto.Changeset.traverse_errors(changeset, fn {message, opts} ->\n" <>
              "    Regex.replace(~r\"%{(\\w+)}\", message, fn _, key ->\n" <>
              "      opts |> Keyword.get(String.to_existing_atom(key), key) |> to_string()\n" <>
              "    end)\n" <>
              "  end)\nend\n\n" <>
              "# In your test:\n" <>
              "assert %{email: [\"can't be blank\"]} = errors_on(changeset)",
          applies_when:
            "Always — the helper exists in any Phoenix-generated app and is trivial to add."
        )
      ],
      references: ["elixir-implementing/SKILL.md#4.2"],
      context: %{},
      file: file,
      line: line
    )
  end
end
